#!/bin/bash

export SERVICE_NAME="call2mqtt"
export SERVICE_DESCRIPTION="Vorota sim800l module ${SERVICE_NAME} service"
export SERVICE_FILENAME="${SERVICE_NAME}.service"
export SERVICE_APP="${SERVICE_NAME}.py"
export SERVICE_DIR=$(realpath "${PWD}/../")


